Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 30

AllCops:
  Exclude:
    - "spec/spec_helper.rb"
    - "lib/spinup/cli.rb"
    - "Gemfile"
    - "Rakefile"
    - "spinup.gemspec"
  TargetRubyVersion: 3.1.4
  NewCops: disable