version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:9081:9081
    volumes:
      - minio:/data
    entrypoint: minio server --address :9080 --console-address :9081 /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin_pass!
      MINIO_SERVER_URL: "http://127.0.0.1:9080"
  
  setup_storage:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./spec/examples:/examples
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9080 admin admin_pass!;
      /usr/bin/mc mb myminio/locale-storage-dev;
      /usr/bin/mc anonymous set download myminio/locale-storage-dev;
      /usr/bin/mc cp /examples/* myminio/locale-storage-dev/;
      exit 0
      "
    

volumes:
  minio:       